version: "3.7"

services:
  origame:
#    restart: always
    build:
      context: ./app/
      dockerfile: Dockerfile.prod
#    command: python manage.py runserver 0.0.0.0:1000
    volumes:
    - ./app/:/usr/src/app/
    ports:
      - 2000:2000
#    env_file:
#      - ./app/.env.dev
    depends_on:
      - origame-db
    links:
      - origame-db
    environment:
      - PORT=2000
  origame-db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=origame
      - POSTGRES_PASSWORD=origame
      - POSTGRES_DB=origame_dev

volumes:
  postgres_data: