# Generated by Django 3.0.5 on 2020-04-21 19:27

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
